[package]
name = "dbc-driver-sqlite"
version = "0.1.0"
edition.workspace = true
description = "SQLite driver for dbc"
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
dbc-core = { path = "../dbc-core" }
rusqlite.workspace = true
tokio.workspace = true
async-trait.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tempfile = "3"
